sudo: required
services:
  - docker

before_install:
  - docker build -t ivanduarte/docker-react -f Dockerfile.dev .

script:
  - docker run ivanduarte/docker-react npm run test -- --coverage

after_success:
  - ping 192.168.0.38
# deploy:
#   provider: elasticbeanstalk